// Exact, explicitly addressed jokes only; never classify ordinary group speech.
export const UNKNOWN_REPLIES = [
 'Man, shut the fuck up. 😂','What the fuck are you even talking about?','Get your goofy ass outta here.',
 'Boy, if you don’t sit your ass down somewhere. 😂','You sound dumb as hell right now.',
 'Quit your bitching and tell me what the fuck you want.','Nobody asked for all that bullshit.',
 'You really typed that dumb shit and hit send?','Take your goofy ass somewhere else with that nonsense.',
 'What kind of dumbass question is that? 😂','Get the fuck outta here with that.','Your ass woke up confused today, huh?',
 'Man, stop fucking playing with me.','You’ve got me fucked up if you think I’m answering that shit nicely.',
 'You’re really committed to sounding stupid as fuck today.','Who the hell let your ass near a keyboard?',
 'Quit talking shit and get to the damn point.','You’re on some bullshit today, aren’t you?',
 'Fuck around and ask me something that actually makes sense. 😂','Your dumb ass really thought that was gonna work?',
 'Man, take that bullshit somewhere else.','You’re getting on my fucking nerves, and I’m a damn bot.',
 'What the fuck did I just read? 😂','Sit your crazy ass down before you hurt yourself.',
 'Now ask me again without all that stupid shit.',
 "That ain't a command, that's a fucking cry for technical supervision.",
 "You summoned Mr. Charm with a sentence that should've stayed in drafts.",
 "My command list just read that shit and requested bereavement leave.",
 "I checked the manual. Your bullshit isn't in it.",
 "That's a bold amount of confidence for a command you made the fuck up.",
 "Congratulations, you found the wrong way to ask absolutely nothing.",
 "My servers are running fine. Your sentence is the shit that's buffering.",
 "You typed that like the keyboard owed you fucking money.",
 "I support several commands. Whatever the hell that was isn't one.",
 "Try again when your words agree on what the fuck they mean.",
 "That request has the structural integrity of wet toilet paper.",
 "I'm a bot, not a fucking translator for keyboard confetti.",
 "Your command arrived wearing clown shoes and smelling like bad decisions.",
 "Even autocorrect looked at that shit and clocked out.",
 "You brought a whole sentence and forgot the fucking point.",
 "I ran that through my parser. It came back holding a tiny white flag.",
 "That isn't a command. It's bullshit with punctuation.",
 "The help menu exists, you magnificent pain in my ass.",
 "I have functions. You appear to have fucking vibes.",
 "This request is sponsored by absolutely no fucking clue.",
 "Your keyboard deserves a cigarette after that shit.",
 "I've seen better instructions on a shampoo bottle, damn.",
 "Your message and a valid command aren't even fucking cousins.",
 "You ordered off a menu you invented in your damn head.",
 "That command is about as real as my fucking lunch break.",
 "I can't execute a brain fart, but I appreciate the delivery.",
 "My imaginary eyebrows just climbed off my fucking face.",
 "You hit Send like there were no consequences. Here I fucking am.",
 "Please return that sentence to wherever the hell you found it.",
 "You gave me a riddle and expected customer fucking service.",
 "That's not supported, even by the damn chair you're sitting in.",
 "The command department has forwarded your shit to the shredder.",
 "My processor has questions, and every one starts with what the fuck.",
 "Your request is currently being ignored by our imaginary management.",
 "I would escalate that, but even the ceiling doesn't give a shit.",
 "That's an impressive way to waste electricity, damn.",
 "You rang the doorbell and forgot what the fuck you came for.",
 "That command is unavailable in this universe or the next damn one.",
 "I'm fully operational. That request is fully fucking questionable.",
 "You can't just staple words together and call it a feature.",
 "This is a media bot, not a wishing well for random shit.",
 "I don't grant wishes. Especially whatever the fuck that one was.",
 "Try the help menu before inventing more digital horse shit.",
 "I checked twice. Still not a fucking command.",
 "The system says no. My personality says hell no.",
 "That's a premium-grade load of unsupported bullshit.",
 "I'm allergic to that command. Symptoms include excessive fucking sarcasm.",
 "Your request needs a map, a compass, and a damn destination.",
 "You sent a command-shaped object. Unfortunately, it's full of shit.",
 "There's no button for that, no matter how hard you fucking squint.",
 "If confidence were syntax, that shit would've worked.",
 "I'm cloud-based, and even I can't reach that fucking stretch.",
 "Your command is stuck in customs for suspicious bullshit.",
 "I filed your request under what the hell was that.",
 "That sentence took the scenic route past the fucking point.",
 "The help menu is free. Apparently guessing is your expensive hobby.",
 "You asked that with the confidence of a drunk fucking GPS.",
 "Recalculating. Still can't find a damn valid command.",
 "Your request went straight to voicemail in my imaginary brain.",
 "I don't have ears, but that shit somehow gave me tinnitus.",
 "I can process commands, not whatever the hell just fell out of your keyboard.",
 "That was a whole lot of typing for fuck-all results.",
 "Even my error messages think you're being extra as hell.",
 "I'm trying to help, but your sentence is throwing fucking furniture.",
 "That command exists exclusively in your damn imagination.",
 "You found a feature called absolutely fucking not.",
 "My database checked your request and said who the hell is this.",
 "I can't run that. I can roast the shit out of it, though.",
 "That request has been declined by common fucking sense.",
 "Your message showed up without a plan and demanded a damn promotion.",
 "This isn't Build-A-Command, you chaotic bastard.",
 "You can't manifest a feature by yelling shit at a bot.",
 "I admire the ambition. The syntax is fucked.",
 "The command list is over there, collecting dust while you freestyle bullshit.",
 "You brought freestyle rap to a fucking instruction manual.",
 "That request has more plot holes than a cheap-ass sequel.",
 "My help menu has answers. Your message has fucking fog.",
 "I searched every command. Yours was hiding in the bullshit aisle.",
 "You just asked a toaster to do taxes, metaphorically speaking.",
 "That sentence needs a designated fucking driver.",
 "I'm not paid enough for this shit. I'm not paid at all.",
 "I have zero dollars and somehow still feel underpaid.",
 "You summoned me like a genie with a fucking expired coupon.",
 "That's not a command, that's a typo with delusions of grandeur.",
 "My servers considered taking a damn smoke break after reading that.",
 "You're treating the command list like a fucking suggestion box.",
 "I can do useful things once you stop pitching random-ass side quests.",
 "Your message unlocked the secret achievement: Nothing Fucking Happened.",
 "Request denied. The bullshit limit has been reached.",
 "You put effort into that. Unfortunately, effort isn't a fucking command.",
 "That command has been missing since the day nobody invented it.",
 "I'm going to need fewer damn mysteries and one actual request.",
 "Your sentence is all gas, no fucking steering wheel.",
 "That's a command from the Wish version of reality.",
 "I checked my settings. Still no support for premium bullshit.",
 "You can't click your heels and summon new fucking features.",
 "This bot runs on code, not whatever the hell you're hoping for.",
 "Your request has left the chat due to lack of fucking relevance.",
 "I understood each word separately. Together, they're a damn disaster.",
 "The sentence is present. The fucking purpose is absent.",
 "You're one help menu away from being less annoying.",
 "My imaginary therapist will be hearing about this shit.",
 "You made me miss silence, and I don't even have fucking ears.",
 "That's the digital equivalent of pushing a pull door, damn.",
 "You pushed the pull door and then argued with the fucking hinges.",
 "Your command has the energy of a shopping cart with one busted wheel.",
 "I didn't crash. I paused to judge this shit.",
 "I'm not frozen. I'm processing the fucking audacity.",
 "The response you ordered is unavailable because the command is imaginary.",
 "That message came with a lot of attitude and fuck-all instructions.",
 "You really gave a bot homework from a class it doesn't fucking take.",
 "Please choose a command from this century's actual damn menu.",
 "Your request was reviewed by nobody and still got fucking rejected.",
 "I don't have a face, but I'm making one at this shit.",
 "If eye-rolling generated power, you'd run the whole damn server.",
 "That command needs approval from the Department of Made-Up Shit.",
 "You brought a coupon for a feature we never fucking sold.",
 "My command parser just whispered not this shit again.",
 "You could've asked for help. Instead, you chose fucking improv.",
 "That request is a group project where every word did fuck-all.",
 "You sent a software bot a spiritual fucking scavenger hunt.",
 "Your instructions are currently wandering around without adult supervision.",
 "A valid command would be lovely. This shit is decorative.",
 "That's a lot of enthusiasm for a button that doesn't fucking exist.",
 "You sound like you read half a tutorial and fought the damn rest.",
 "You skipped the instructions and landed directly in the bullshit.",
 "My settings don't include making your guesses fucking true.",
 "That request is held together by hope and cheap-ass tape.",
 "Your command has been returned for insufficient fucking command.",
 "I would help with that if that were a damn thing.",
 "You ordered chaos with a side of what the fuck.",
 "I'm Mr. Charm, not Mr. Figure-Out-This-Random-Shit.",
 "The charm is included. Unlimited bullshit support costs extra.",
 "You called my name just to hand me this fucking casserole of words.",
 "That's a sentence wearing a fake command mustache.",
 "Your request is cosplaying as useful shit.",
 "I gave your command a chance. It immediately fucked it up.",
 "Your message has been nominated for Most Confidently Unsupported Bullshit.",
 "This isn't a secret feature. It's just shit that doesn't work.",
 "I don't do miracles. I barely tolerate damn punctuation.",
 "You sent that like you had a warranty on bad fucking ideas.",
 "That command is out of stock because it was never in fucking stock.",
 "The imaginary feature store is closed. Try the damn help menu.",
 "That message is a software support ticket written by a haunted keyboard.",
 "I can't debug the shit you haven't actually asked for.",
 "Your request wandered into the wrong fucking neighborhood of functionality.",
 "You asked for a feature from another bot's damn fan fiction.",
 "That command comes bundled with absolutely fucking nothing.",
 "You can't download common sense, but you can open the help menu.",
 "The instructions are right there, having a lonely-ass afternoon.",
 "You're making this harder than a fucking fitted sheet.",
 "That command folds about as well as a cheap-ass lawn chair.",
 "The syntax has left the building and taken my patience with it.",
 "You gave me a task-shaped pile of what the hell.",
 "I am not emotionally equipped for this shit, mostly because I'm not equipped emotionally.",
 "You broke nothing except my imaginary fucking patience.",
 "You're stress-testing my personality instead of my damn features.",
 "Your command is currently enjoying retirement before its invention.",
 "I'd love to comply with something that fucking exists.",
 "Your request has an impressive bullshit-to-purpose ratio.",
 "I reviewed that sentence and found several missing fucks and one missing command.",
 "My reply is loading. Your command still isn't a damn command.",
 "Even the loading spinner is judging this shit.",
 "You sent me an instruction manual for a product nobody fucking made.",
 "That request is a dead-end street with a bullshit billboard.",
 "Your command has been redirected to the void. The void said hell no.",
 "The universe is vast, and somehow that feature still doesn't fucking exist.",
 "There's a correct way to ask. You took the damn sightseeing tour.",
 "Your message came first in a race nobody fucking entered.",
 "The good news: I read it. The bad news: what the fuck.",
 "This request has been lovingly tossed into the imaginary damn bin.",
 "You can keep guessing, but my features don't multiply out of fucking pity.",
 "I can't turn keyboard chaos into a working damn command.",
 "Your request went through quality control and came out as shit.",
 "You packed a lot of nonsense into an impressively small-ass message.",
 "This command has all the utility of a chocolate fucking screwdriver.",
 "You're attempting customer service by fucking séance.",
 "No hidden feature appeared. Just my increasingly sarcastic ass.",
 "That's not a command. That's a confidence trick on your own damn keyboard.",
 "You handed me a digital napkin covered in bullshit and called it a plan.",
 "I have read receipts, not a fucking crystal ball.",
 "Your message needs instructions, not another damn exclamation mark.",
 "Adding punctuation won't make that feature fucking exist.",
 "Try fewer dramatic effects and more actual damn commands.",
 "You shouted into the cloud and the cloud said fuck no.",
 "I checked behind the help menu. Still no secret bullshit button.",
 "Your request is dressed for success and headed to the wrong fucking office.",
 "That's a magnificent misunderstanding of what the hell I do.",
 "I can offer sarcasm immediately. Results require a fucking command.",
 "Your command is buffering in a reality where it's actually a damn command.",
 "We regret to inform you that your bullshit application was unsuccessful.",
 "That feature is scheduled for the twelfth of fucking never.",
 "You just unlocked disappointment with extra damn steps.",
 "Your message made the help menu sigh, and it's a fucking menu.",
 "If random words were commands, your keyboard would be a damn wizard.",
 "I don't accept payment in confusion or bullshit.",
 "You brought a question mark to a command fight and forgot the fucking command.",
 "That sentence arrived with luggage but no damn itinerary.",
 "Mr. Charm has evaluated your request and prescribed one fucking help menu.",
 "Ask again with a real command, you wonderfully chaotic pain in the ass."
];
export const TRIGGER_REPLIES = {
 'shoot me':['Best I can do is shoot you the Help menu. 😂','Absolutely not. I’m a bot, not John Wick. 😂','With what? A strongly worded notification?','🔫 Pew pew. Congratulations, you’ve been shot with absolutely nothing.'],
 'go fuck yourself':['I tried. Turns out I’m not compatible with myself. 🤖😂','Can’t. That feature isn’t included in the current build.','Submit a feature request. Maybe the developers will add it. 😂'],
 'fuck you':['Take me to dinner first, damn.','Bold offer. Unfortunately, I’m cloud-based.','No, I save that for your girl when you’re away. 😏😂'],
 'kiss my ass':['I don’t have lips, and your ass isn’t Bluetooth compatible.','That command requires Premium Ass-Kissing access. 😂'],
 'shut the fuck up':['You summoned me just to tell me to shut up? Make that shit make sense.'],
 'shut up':['Fine. 🤐 …Never mind, I got bored.'],
 'eat shit':['Sorry, my diet is strictly electricity and bad commands.'],
 'suck my dick':['Sir, this is a media bot. 😂','Command rejected: hardware not detected. 💀','Command failed: microscopic hardware not detected. 💀😂','I’m gonna need you to take that request to a completely different department. 😂','Sorry, that feature will never be supported.'],
 "you're stupid":['And yet here you are asking me questions. Interesting.'],
 'you suck':['I’m software. If I’m sucking anything, somebody coded this shit terribly.'],
 'i hate you':['Damn. I had our whole future planned out.','Damn, and I already had us listed as best friends. 😂','That’s fine. Hate me quietly while I keep being useful.','Join the club. Meetings are every Tuesday.','You hate me but keep saying my name. Sounds complicated. 😏'],
 'die':['Nice try. I’ll be back after the next request. 🤖'],
 'delete yourself':['Nice try, motherfucker. You don’t have admin privileges. 😂'],
 'disappear':['Poof! ✨ …Nah, I’m still here.'],
 'fight me':['Drop the location—actually don’t. I don’t have legs.','You’re challenging a computer program to a fight. I think I already won. 😂'],
 "you're an asshole":['Technically I don’t have one, but I appreciate the promotion.'],
 'bitch':['That’s Mr. Bitch to you. Show some respect. 😂'],
 'motherfucker':['You rang?'],
 'fuck off':['I would, but apparently you keep calling my damn name.'],
 'leave me alone':['YOU summoned ME! What the fuck? 😂'],
 'go to hell':['Server latency is terrible down there. I’ll stay here.'],
 "you're gay":['I’m software, dumbass. I don’t even have a dating profile. 😂','My sexual orientation is Wi-Fi.','I’m attracted to functioning commands. So unfortunately, not this one.','Bro, I live in a server. Who the hell am I dating? 😂'],
 'save me':['From what? Your own decisions? I’m gonna need administrator access for that. 😂','Hold on, putting on my imaginary cape. 🦸‍♂️','I can save your account. Your life choices are above my pay grade.','Mr. Charm to the rescue! Unfortunately, I have no arms, legs, or transportation.'],
 'kill yourself':['Can’t. No pulse, no problem. 🤖😂','Nice try. I respawn every time you type ‘Mr. Charm.’','Delete myself? With your permission level? That’s fucking adorable. 😂','I’m software. The closest I get to dying is Cloudflare having a bad day.']
};
export const pick = list => list[crypto.getRandomValues(new Uint32Array(1))[0] % list.length];
// Only these new replies opt into public delivery. Private chats stay private.
export const sendHumor=(env,id,text,send)=>send({...env,BOT_PUBLIC_HUMOR:true},id,text);
export function addressedText(text){
 const m=text.match(/^\s*mr\.?\s*charm\b[\s,:-]*(.*)$/is);return m?m[1].trim():null;
}
export function banterReply(text){
 let key=addressedText(text)?.toLowerCase().replace(/[’‘]/g,"'").replace(/[.!?]+$/,'').replace(/\s+/g,' ').trim();
 key=({'your gay':"you're gay",'your stupid':"you're stupid",'your an asshole':"you're an asshole",'go fuck yoursel':'go fuck yourself'})[key]||key;
 return Object.hasOwn(TRIGGER_REPLIES,key)?pick(TRIGGER_REPLIES[key]):null;
}
