"""Exact cache-lifecycle changes reviewed after Build 129; no transport exemption."""

CACHE_LIFECYCLE_REPAIRS = (('/** Shared LRU order for positive and negative window rows. */\n'
  'let programmeWindowAccessOrder = new Set<string>();\n'
  'let programmeWindowCacheKey = "";\n'
  '/** Coalesce overlapping warm/viewport reads so one channel is never queried twice. */\n'
  'const programmeWindowInFlight = new Map<string, Promise<void>>();\n'
  'let lastNativeMatchWriteFingerprint = "";\n',
  '/** Shared LRU order for positive and negative window rows. */\n'
  'let programmeWindowAccessOrder = new Set<string>();\n'
  'let programmeWindowCacheKey = "";\n'
  '/** Invalidates pending reads without discarding the retained focus rows. */\n'
  'let programmeWindowGeneration = 0;\n'
  '/** Coalesce overlapping warm/viewport reads so one channel is never queried twice. */\n'
  'const programmeWindowInFlight = new Map<string, Promise<void>>();\n'
  'let lastNativeMatchWriteFingerprint = "";\n'),
 ('  programmeWindowEmptyKeys.clear();\n'
  '  programmeWindowAccessOrder.clear();\n'
  '  programmeWindowCacheKey = "";\n'
  '  // In-flight native reads cannot be cancelled, but their cache-key guard keeps\n'
  '  // them from merging stale results after this reset. Let new-window reads start.\n'
  '  programmeWindowInFlight.clear();\n'
  '}\n'
  '\n',
  '  programmeWindowEmptyKeys.clear();\n'
  '  programmeWindowAccessOrder.clear();\n'
  '  programmeWindowCacheKey = "";\n'
  '  invalidateProgrammeWindowReads();\n'
  '}\n'
  '\n'
  'function invalidateProgrammeWindowReads(): void {\n'
  '  // Native bridge reads can finish late. A generation also rejects resets that\n'
  '  // return to the same window key, while leaving retained focus rows intact.\n'
  '  programmeWindowGeneration += 1;\n'
  '  programmeWindowInFlight.clear();\n'
  '}\n'
  '\n'),
 ('  keepIds: string[] = [],\n'
  '  critical = false,\n'
  '): void {\n'
  '  const previous = maxProgrammeWindowKeys;\n'
  '  maxProgrammeWindowKeys = critical\n'
  '    ? Math.max(128, keepIds.length)\n',
  '  keepIds: string[] = [],\n'
  '  critical = false,\n'
  '): void {\n'
  '  invalidateProgrammeWindowReads();\n'
  '  const previous = maxProgrammeWindowKeys;\n'
  '  maxProgrammeWindowKeys = critical\n'
  '    ? Math.max(128, keepIds.length)\n'),
 ('  if (!requested.length || !nativeEpgAvailable) return {};\n'
  '\n'
  '  const requestCacheKey = programmeWindowCacheKey;\n'
  '  const owned: string[] = [];\n'
  '  const waits = new Set<Promise<void>>();\n'
  '  for (const id of requested) {\n'
  '    if (hasCachedProgrammeResult(id)) continue;\n'
  '    const inFlightKey = `${requestCacheKey}|${id}`;\n'
  '    const existing = programmeWindowInFlight.get(inFlightKey);\n'
  '    if (existing) waits.add(existing);\n'
  '    else owned.push(id);\n',
  '  if (!requested.length || !nativeEpgAvailable) return {};\n'
  '\n'
  '  const requestCacheKey = programmeWindowCacheKey;\n'
  '  const requestGeneration = programmeWindowGeneration;\n'
  '  const isCurrentRequest = () => programmeWindowCacheKey === requestCacheKey && programmeWindowGeneration '
  '=== requestGeneration;\n'
  '  const owned: string[] = [];\n'
  '  const waits = new Set<Promise<void>>();\n'
  '  for (const id of requested) {\n'
  '    if (hasCachedProgrammeResult(id)) continue;\n'
  '    const inFlightKey = `${requestGeneration}|${requestCacheKey}|${id}`;\n'
  '    const existing = programmeWindowInFlight.get(inFlightKey);\n'
  '    if (existing) waits.add(existing);\n'
  '    else owned.push(id);\n'),
 ('  if (owned.length) {\n'
  '    const task = (async () => {\n'
  '      const joined = await queryNativeGuideWindow(owned, startMs, endMs);\n'
  '      const merged: Record<string, Program[]> = { ...joined };\n'
  '      const missingAfterJoin = owned.filter((id) => !merged[id]?.length);\n'
  '\n',
  '  if (owned.length) {\n'
  '    const task = (async () => {\n'
  '      const joined = await queryNativeGuideWindow(owned, startMs, endMs);\n'
  '      if (!isCurrentRequest()) return;\n'
  '      const merged: Record<string, Program[]> = { ...joined };\n'
  '      const missingAfterJoin = owned.filter((id) => !merged[id]?.length);\n'
  '\n'),
 ('          getEpgSourcePreferences(),\n'
  '          getMultiEpgSources(),\n'
  '        ]);\n'
  '        const customOwned = new Set<string>();\n'
  '        if (ownership.userEnabled && ownership.userUrl) {\n'
  '          for (const channelId of Object.keys(ownership.userOverrides)) customOwned.add(channelId);\n',
  '          getEpgSourcePreferences(),\n'
  '          getMultiEpgSources(),\n'
  '        ]);\n'
  '        if (!isCurrentRequest()) return;\n'
  '        const customOwned = new Set<string>();\n'
  '        if (ownership.userEnabled && ownership.userUrl) {\n'
  '          for (const channelId of Object.keys(ownership.userOverrides)) customOwned.add(channelId);\n'),
 ('          }\n'
  '          if (xmltvIds.length) {\n'
  '            const byXmltv = await loadNativeEpgWindow(xmltvIds, startMs, endMs);\n'
  '            for (const playlistId of primaryFallbackIds) {\n'
  '              const xmltvId = (byId.get(playlistId)?.tvg_id || playlistId).trim();\n'
  '              const list = byXmltv[xmltvId];\n',
  '          }\n'
  '          if (xmltvIds.length) {\n'
  '            const byXmltv = await loadNativeEpgWindow(xmltvIds, startMs, endMs);\n'
  '            if (!isCurrentRequest()) return;\n'
  '            for (const playlistId of primaryFallbackIds) {\n'
  '              const xmltvId = (byId.get(playlistId)?.tvg_id || playlistId).trim();\n'
  '              const list = byXmltv[xmltvId];\n'),
 ('        }\n'
  '      }\n'
  '\n'
  '      // A date/epoch change may finish while SQLite is reading. Never merge an\n'
  '      // old window into the newly cleared cache.\n'
  '      if (programmeWindowCacheKey === requestCacheKey) {\n'
  '        mergeProgrammeQueryResult(owned, merged);\n'
  '      }\n'
  '    })();\n'
  '    for (const id of owned) programmeWindowInFlight.set(`${requestCacheKey}|${id}`, task);\n'
  '    const cleanup = () => {\n'
  '      for (const id of owned) {\n'
  '        const inFlightKey = `${requestCacheKey}|${id}`;\n'
  '        if (programmeWindowInFlight.get(inFlightKey) === task) {\n'
  '          programmeWindowInFlight.delete(inFlightKey);\n'
  '        }\n',
  '        }\n'
  '      }\n'
  '\n'
  '      // A date/epoch change or release may finish while SQLite is reading.\n'
  '      // Never let the old read refill the newly cleared or trimmed cache.\n'
  '      if (isCurrentRequest()) {\n'
  '        mergeProgrammeQueryResult(owned, merged);\n'
  '      }\n'
  '    })();\n'
  '    for (const id of owned) programmeWindowInFlight.set(`${requestGeneration}|${requestCacheKey}|${id}`, '
  'task);\n'
  '    const cleanup = () => {\n'
  '      for (const id of owned) {\n'
  '        const inFlightKey = `${requestGeneration}|${requestCacheKey}|${id}`;\n'
  '        if (programmeWindowInFlight.get(inFlightKey) === task) {\n'
  '          programmeWindowInFlight.delete(inFlightKey);\n'
  '        }\n'),
 ('\n'
  '  if (waits.size) await Promise.all(waits);\n'
  '  const result: Record<string, Program[]> = {};\n'
  '  if (programmeWindowCacheKey !== requestCacheKey) return result;\n'
  '  for (const id of requested) {\n'
  '    const list = programmeWindowCache[id];\n'
  '    if (list?.length) result[id] = list;\n',
  '\n'
  '  if (waits.size) await Promise.all(waits);\n'
  '  const result: Record<string, Program[]> = {};\n'
  '  if (!isCurrentRequest()) return result;\n'
  '  for (const id of requested) {\n'
  '    const list = programmeWindowCache[id];\n'
  '    if (list?.length) result[id] = list;\n'),
 ('    clearProgrammeWindowCache();\n'
  '    programmeWindowCacheKey = cacheKey;\n'
  '  }\n'
  '\n'
  '  const remapped = withManualRemaps(parsed.channels);\n'
  '\n',
  '    clearProgrammeWindowCache();\n'
  '    programmeWindowCacheKey = cacheKey;\n'
  '  }\n'
  '  const requestGeneration = programmeWindowGeneration;\n'
  '\n'
  '  const remapped = withManualRemaps(parsed.channels);\n'
  '\n'),
 ('  // A background EPG refresh can replace the cache while SQLite is reading.\n'
  '  // Returning explicit empty rows here would erase the last-good Guide even\n'
  '  // though the old query correctly refused to merge into the new epoch.\n'
  '  if (programmeWindowCacheKey !== cacheKey) return {};\n'
  '  const delta: Record<string, Program[]> = {};\n'
  '  for (const id of unique) {\n'
  '    const cached = programmeWindowCache[id];\n',
  '  // A background EPG refresh can replace the cache while SQLite is reading.\n'
  '  // Returning explicit empty rows here would erase the last-good Guide even\n'
  '  // though the old query correctly refused to merge into the new epoch.\n'
  '  if (programmeWindowCacheKey !== cacheKey || programmeWindowGeneration !== requestGeneration) return '
  '{};\n'
  '  const delta: Record<string, Program[]> = {};\n'
  '  for (const id of unique) {\n'
  '    const cached = programmeWindowCache[id];\n'))

def normalize_audited_guide_cache_lifecycle(source: str) -> str:
    """Unrecognized changes stay visible to the pinned transport comparison."""
    for before, after in CACHE_LIFECYCLE_REPAIRS:
        if source.count(after) == 1:
            source = source.replace(after, before, 1)
    return source
